stages:
- test
- build

before_script:
  - go get -t ./...

test:
  script:
    - go test ./...

.build: &build
  script:
    - go build -o docker-machine-driver-bytemark
    - zip docker-machine-driver-bytemark-$GOOS-$GOARCH.zip
  artifacts:
    paths:
      - ./docker-machine-driver-bytemark-$GOOS-$GOARCH.zip
    expire_in: '1 week'

build-linux-amd64: 
  <<: *build
  variables:
    - GOOS=linux
    - GOARCH=amd64

build-darwin-amd64:
  <<: *build
  variables:
    - GOOS=darwin
    - GOARCH=amd64
