stages:
  - test
  - build

image: golang:1.11-stretch

before_script:
  - mkdir -p $GOPATH/src/github.com/BytemarkHosting/docker-machine-driver-bytemark
  - cp -r * .* $GOPATH/src/github.com/BytemarkHosting/docker-machine-driver-bytemark
  - go get -t github.com/BytemarkHosting/docker-machine-driver-bytemark/...

test:
  script:
    - go test github.com/BytemarkHosting/docker-machine-driver-bytemark/...

.build: &build
  stage: build
  before_script:
    - apt update
    - apt install zip
  script:
    - go build github.com/BytemarkHosting/docker-machine-driver-bytemark -o docker-machine-driver-bytemark
    - zip docker-machine-driver-bytemark-$GOOS-$GOARCH.zip
  artifacts:
    paths:
      - ./docker-machine-driver-bytemark-$GOOS-$GOARCH.zip
    expire_in: '1 week'

build-linux-amd64: 
  <<: *build
  variables:
    GOOS: linux
    GOARCH: amd64

build-darwin-amd64:
  <<: *build
  variables:
    GOOS: darwin
    GOARCH: amd64
