language: go

sudo: false

go:
  - 1.10

install:
  - go install
    
# check that bytemark-disc flag is listed in help (i.e. driver loads fine)
script:
  - cp $GOPATH/bin/docker-machine-driver-bytemark .
  - docker-machine create -d bytemark -h | grep bytemark-cores

deploy:
  provider: releases
  api_key:
    secure:
  file: "docker-machine-driver-bytemark"
  skip_cleanup: true
  on:
    tags: true
